/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spc.edu;

import javax.swing.JOptionPane;

/**
 *
 * @author SPC
 */
public class Caro extends javax.swing.JFrame {

    /**
     * Creates new form Caro
     */
    int turn = 2;
    int buttonnused[]= {0,0,0,0,0,0,0,0,0};
    int pXwon[] = {0,0,0,0,0,0,0,0,0};
    int pWoxn[] = {0,0,0,0,0,0,0,0,0};
    
    int pXwon(){
        if(pXwon[0] == 1 && pXwon[1] == 1 && pXwon[2] == 2 ){
            return 1;
        }
        if(pXwon[3] == 1 && pXwon[4] == 1 && pXwon[5] == 2 ){
            return 1;
        }
        if(pXwon[6] == 1 && pXwon[7] == 1 && pXwon[8] == 2 ){
            return 1;
        }
        if(pXwon[0] == 1 && pXwon[3] == 1 && pXwon[6] == 2 ){
            return 1;
        }
        if(pXwon[1] == 1 && pXwon[4] == 1 && pXwon[7] == 2 ){
            return 1;
        }
        if(pXwon[0] == 1 && pXwon[1] == 1 && pXwon[2] == 2 ){
            return 1;
        }
        if(pXwon[2] == 1 && pXwon[5] == 1 && pXwon[8] == 2 ){
            return 1;
        }
        if(pXwon[2] == 1 && pXwon[4] == 1 && pXwon[6] == 2 ){
            return 1;
        }
        if(pXwon[0] == 1 && pXwon[4] == 1 && pXwon[8] == 2 ){
            return 1;
        }
        return 0;
    }
    int pWoxn(){
        if(pWoxn[0] == 1 && pWoxn[1] == 1 && pWoxn[2] == 2 ){
            return 1;
        }
        if(pWoxn[3] == 1 && pWoxn[4] == 1 && pWoxn[5] == 2 ){
            return 1;
        }
        if(pWoxn[6] == 1 && pWoxn[7] == 1 && pWoxn[8] == 2 ){
            return 1;
        }
        if(pWoxn[0] == 1 && pWoxn[3] == 1 && pWoxn[6] == 2 ){
            return 1;
        }
        if(pWoxn[1] == 1 && pWoxn[4] == 1 && pWoxn[7] == 2 ){
            return 1;
        }
        if(pWoxn[0] == 1 && pWoxn[1] == 1 && pWoxn[2] == 2 ){
            return 1;
        }
        if(pWoxn[2] == 1 && pWoxn[5] == 1 && pWoxn[8] == 2 ){
            return 1;
        }
        if(pWoxn[2] == 1 && pWoxn[4] == 1 && pWoxn[6] == 2 ){
            return 1;
        }
        if(pWoxn[0] == 1 && pWoxn[4] == 1 && pWoxn[8] == 2 ){
            return 1;
        }
        return 0;
    }
    
    public Caro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();

        jButton10.setText("jButton10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if( buttonnused[0] == 0){
            if(turn % 2 == 0){
                turn++;
                b0.setText("X");
                 buttonnused[0] = 1;
                 pXwon[0] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b0.setText("O");
                 buttonnused[0] = 1;
                 
                 pWoxn[0] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        
        if( buttonnused[1] == 0){
            if(turn % 2 == 0){
                turn++;
                b1.setText("X");
                 buttonnused[1] = 1;
                 pXwon[1] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b1.setText("O");
                 buttonnused[1] = 1;
                 
                 pWoxn[1] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        
        if( buttonnused[2] == 0){
            if(turn % 2 == 0){
                turn++;
                b2.setText("X");
                 buttonnused[2] = 1;
                 pXwon[2] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b0.setText("O");
                 buttonnused[2] = 1;
                 
                 pWoxn[2] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        
        if( buttonnused[3] == 0){
            if(turn % 2 == 0){
                turn++;
                b3.setText("X");
                 buttonnused[3] = 1;
                 pXwon[3] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b3.setText("O");
                 buttonnused[3] = 1;
                 
                 pWoxn[3] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        
        if( buttonnused[4] == 0){
            if(turn % 2 == 0){
                turn++;
                b4.setText("X");
                 buttonnused[4] = 1;
                 pXwon[4] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b4.setText("O");
                 buttonnused[4] = 1;
                 
                 pWoxn[4] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        
        if( buttonnused[5] == 0){
            if(turn % 2 == 0){
                turn++;
                b5.setText("X");
                 buttonnused[5] = 1;
                 pXwon[5] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b5.setText("O");
                 buttonnused[5] = 1;
                 
                 pWoxn[5] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        
        if( buttonnused[6] == 0){
            if(turn % 2 == 0){
                turn++;
                b6.setText("X");
                 buttonnused[6] = 1;
                 pXwon[6] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b6.setText("O");
                 buttonnused[6] = 1;
                 
                 pWoxn[6] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        
        if( buttonnused[7] == 0){
            if(turn % 2 == 0){
                turn++;
                b7.setText("X");
                 buttonnused[7] = 1;
                 pXwon[7] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b7.setText("O");
                 buttonnused[7] = 1;
                 
                 pWoxn[7] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if( buttonnused[8] == 0){
            if(turn % 2 == 0){
                turn++;
                b8.setText("X");
                 buttonnused[8] = 1;
                 pXwon[8] = 1;
                 
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }else{
                turn++;
                b8.setText("O");
                 buttonnused[8] = 1;
                 
                 pWoxn[8] = 1;
                 int resultX = pXwon();
                 int resultO = pWoxn();
                 
                 if(resultX == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player X won !!!");
                 }else if(resultO == 1){
                     JOptionPane.showMessageDialog(rootPane, "Player O won !!!");
                 }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Mày Đổi Nút Khác Đi");
        }
    }//GEN-LAST:event_b8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton jButton10;
    // End of variables declaration//GEN-END:variables
}
