/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spc.edu;

import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author PC
 */
public class TinhTienDien extends javax.swing.JFrame {

    /**
     * Creates new form TinhTienDien
     */
    public TinhTienDien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbChiSoCu = new javax.swing.JLabel();
        lbChiSoMoi = new javax.swing.JLabel();
        lbDienNang = new javax.swing.JLabel();
        txtChiSoCu = new javax.swing.JTextField();
        txtChiSoMoi = new javax.swing.JTextField();
        txtDienNang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        btTinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbChiSoCu.setText("Chỉ Số Cũ ");

        lbChiSoMoi.setText("Chỉ Số Mới ");

        lbDienNang.setText("Điện Năng");

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        btTinh.setText("Tính");
        btTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btTinh)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbChiSoCu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChiSoCu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbChiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDienNang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChiSoMoi)
                                    .addComponent(txtDienNang))))
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbChiSoCu)
                    .addComponent(txtChiSoCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbChiSoMoi)
                    .addComponent(txtChiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDienNang)
                    .addComponent(txtDienNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btTinh)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTinhActionPerformed
        // TODO add your handling code here:
        int [] BacTieuThu = {50, 100, 200, 300};
        double [] GiaDien = {1678, 1734, 2014, 2536};
        int Chisomoi, Chisocu;
        try{
            Chisomoi = Integer.parseInt(txtChiSoMoi.getText());
            Chisocu = Integer.parseInt(txtChiSoCu.getText());
            
            if(Chisomoi < Chisocu){
                 JOptionPane.showMessageDialog(this,"Chỉ số mới phải lớn hơn chỉ số cũ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                 return;
            }
            
            int Diennang = Chisomoi - Chisocu;
            txtDienNang.setText(String.valueOf(Diennang));
            double SumMoney = 0;
            int Diennangconlai = Diennang;
            
            ArrayList <String> listData = new ArrayList<>();
            
            for(int i = 0; i < BacTieuThu.length; i++){
                if(Diennangconlai > 0){
                    int SoDienBac = Math.min(Diennangconlai, BacTieuThu[i]);
                    double TienDienTheoBac = SoDienBac * GiaDien[i];
                    
                    SumMoney += TienDienTheoBac;
                    listData.add(String.format("Bậc %d: %d kWh * %.2f VND = %.2f VND", 
                    (i + 1), SoDienBac, GiaDien[i], TienDienTheoBac));
                
                    Diennangconlai -= SoDienBac;
                }
                if(Diennangconlai > 0){
                    double tienvuot = Diennangconlai * GiaDien[GiaDien.length - 1];
                    SumMoney += tienvuot;
                    listData.add(String.format("Bậc 5: %d kWh * %.2f VND = %.2f VND", 
                Diennangconlai, GiaDien[GiaDien.length - 1], tienvuot));
                    
                }
               listData.add(String.format("Tổng tiền điện: %.2f VND", SumMoney));
                
                list.setListData(listData.toArray(new String[0]));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Số", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_btTinhActionPerformed

    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhTienDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTinh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbChiSoCu;
    private javax.swing.JLabel lbChiSoMoi;
    private javax.swing.JLabel lbDienNang;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField txtChiSoCu;
    private javax.swing.JTextField txtChiSoMoi;
    private javax.swing.JTextField txtDienNang;
    // End of variables declaration//GEN-END:variables
}
